# Generated by Django 4.2 on 2024-02-04 01:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('dob', models.CharField(blank=True, max_length=255)),
                ('SIN', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('completed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landlord_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('rental_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentoro.landlordprofile')),
            ],
            options={
                'db_table': 'rental_property',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalPropertyTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(blank=True, max_length=255)),
                ('transaction_slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'rental_property_transaction_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalPropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255)),
                ('type_slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'rental_property_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('dob', models.CharField(blank=True, max_length=255)),
                ('SIN', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('completed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalPropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=255)),
                ('unit_id', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentoro.rentalproperty')),
                ('tenant', models.ManyToManyField(to='rentoro.tenantprofile')),
            ],
            options={
                'db_table': 'rental_property_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalPropertyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentoro.rentalpropertyunit')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentoro.rentalpropertytransactiontype')),
            ],
            options={
                'db_table': 'rental_property_transaction',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentoro.rentalpropertytype'),
        ),
    ]
