# Generated by Django 4.2 on 2024-03-15 01:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentoro', '0002_rentalpropertytransactiontype_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.CharField(blank=True, max_length=6)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPropertyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=100)),
                ('expire_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentoro.rentalproperty')),
            ],
        ),
    ]
