# Generated by Django 4.2 on 2024-03-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rentoro', '0004_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='RentoroUser',
        ),
    ]
