# Generated by Django 4.2 on 2024-01-20 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('open_date', models.DateTimeField(blank=True, max_length=255)),
                ('closed_date', models.DateTimeField(blank=True, max_length=255)),
                ('investment_type', models.CharField(blank=True, max_length=100)),
                ('add_type', models.CharField(blank=True, max_length=100)),
                ('compound_type', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'investor_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('dob', models.CharField(blank=True, max_length=255)),
                ('SIN', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('completed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investor_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorAccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_bank', fernet_fields.fields.EncryptedTextField()),
                ('transfer_account_number', fernet_fields.fields.EncryptedTextField()),
                ('transfer_type', fernet_fields.fields.EncryptedTextField()),
                ('transfer_amount', fernet_fields.fields.EncryptedTextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investo.investoraccount')),
            ],
            options={
                'db_table': 'investor_account_transfer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('transaction_name', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(blank=True, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investo.investoraccount')),
            ],
            options={
                'db_table': 'investor_account_transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorAccountMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=255)),
                ('meta_value', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investo.investoraccount')),
            ],
            options={
                'db_table': 'investor_account_meta',
            },
        ),
        migrations.CreateModel(
            name='InvestorAccountDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_institution_number', fernet_fields.fields.EncryptedTextField()),
                ('account_institution_name', fernet_fields.fields.EncryptedTextField()),
                ('account_transit_number', fernet_fields.fields.EncryptedTextField()),
                ('account_account_number', fernet_fields.fields.EncryptedTextField()),
                ('account_deposit_amount', fernet_fields.fields.EncryptedTextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investo.investoraccount')),
            ],
            options={
                'db_table': 'investor_account_deposit',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='investor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investo.investorprofile'),
        ),
    ]
