# Generated by Django 4.2 on 2024-01-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investo', '0003_investolicense_investolicensetype_managerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investolicense',
            name='user',
        ),
        migrations.AddField(
            model_name='investolicense',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investo.managerprofile'),
        ),
    ]
